name: 02 - workflow event

on:

    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the tigger
              run: echo "I have been tiggered by a(n) ${{ github.event_name }} event."


