name: 03 -workflow runner
on: 
  push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show OS
              run: |
                echo "this runs on ununtu runner"
                 echo "Runner OS: $RUNNER_OS"