name: 04 - Using action
on:
    push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: '20.x'
      - name: Install dependency
        run: npm ci
        working-directory: 04-using-action/react-app
      



        # 0. checkout the repository
        # 1. Installing deps of our react appliaction
        # 2. Execute automate test
