name: 04 - Using action
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: .github/workflows/04-using-action/react-app  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: '20.x'
      - name: Install dependency
        run: npm ci
        
      - name: Run Test
        run: npm run test
        



        # 0. checkout the repository
        # 1. Installing deps of our react appliaction
        # 2. Execute automate test
